import { TicTacToe } from './js/game.js';
import { ResultTemplate } from './js/resultTemplate.js';
import * as helpers from './js/helpers.js';

const socket = io.connect('http://localhost:4001/');
// var socket = io.connect('https://tictactoews.herokuapp.com:443/');

const resultTemplate = new ResultTemplate();
let gamesList = [];
// let game = {
//     gameId: null
// }
// console.log(game)
// set or get localStorage uuid
socket.on('connected players', numberOfOnlinePlayers => {
    if (localStorage.getItem("uuid") === null) {
        localStorage.setItem('uuid', helpers.uuidv4());
    }
    connectedPlayers.innerHTML = numberOfOnlinePlayers;
});

createRoom.onclick = () => {
    const index = gamesList.map(e => e.gameId).indexOf(localStorage.getItem('uuid'));
    if (index === -1) {
        socket.emit('generate room', localStorage.getItem('uuid'));
    } else {
        console.log('You have already created a game');
    }
}

socket.on('games', games => {
    gamesList = games;
    roomsList.innerHTML = '';
    // console.log(games);

    // populate rooms list
    games.forEach(game => {
        // console.log(game)
        const newGame = document.createElement('button');
        const newContent = document.createTextNode('Game generated by ' + game.gameId);
        newGame.setAttribute('id', game.gameId);
        if (game.players.length >= 2) {
            newGame.setAttribute('disabled', true)
        }
        newGame.appendChild(newContent);
        roomsList.append(newGame);
    });
    // roomsList.innerHTML = gamesList;
});

socket.on('player disconnected', function (data) {
    connectedPlayers.innerHTML = data;
});

let gId = '';

socket.on('room joined', data => {
    if (data.gameId === gId) {
        onlinePlayers.innerHTML = `Online players: ${data.players.length}`;
    }
    const item = document.getElementById(data.gameId);
    if (data.players.length >= 2) {
        item.setAttribute('disabled', true)
    }
})

// socket.on('')
roomsList.onclick = (event) => {
    ticTacToeField.innerHTML = '';
    console.log(event.target)
    gId = event.target.id;
    // current room gameId
    const gameId = event.target.id;
    const playerId = localStorage.getItem("uuid");

    // send gameId and playerId that joined the room
    socket.emit('join room', { gameId, playerId })
    // set game section class equal to gameId and display it
    rooms.style.display = 'none';
    game.setAttribute('class', gameId);
    const currentGame = document.getElementsByClassName(gameId);
    currentGame[0].style.display = 'block';
    gameIdContainer.innerHTML = gameId;

    // create new instance of ticTacToe with gameId
    let ticTacToe = new TicTacToe(gameId);
    ticTacToe.newGame();
    const getTicTacToe = document.querySelectorAll('#ticTacToeField td');

    socket.on('room joined', data => {
        if (data.players.length === 2) {
            console.log('enabled')
        }
    })

    const makeMove = () => {
        getTicTacToe.forEach((cell, index) => {
            cell.onclick = () => {
                if (!cell.hasChildNodes()) {
                    // send gameId and move cell address
                    socket.emit('move', { index, gameId });
                }
            }
        })
    }


    makeMove();


    // data retruns moves and gameId
    socket.on('move made', function (data) {
        console.log(data)
        if (data.gameId === gameId) {
            if (ticTacToe.turn === 0) {
                getTicTacToe[data.index].innerHTML = resultTemplate.playerOneTemplate;
                ticTacToe.moves[data.index] = 'X';
            } else {
                getTicTacToe[data.index].innerHTML = resultTemplate.playerTwoTemplate;
                ticTacToe.moves[data.index] = 'O';
            }
            // console.log(ticTacToe.moves);
            ticTacToe.checkWinner(ticTacToe.turn, ticTacToe.moves);
            if (!ticTacToe.turn) {
                ticTacToe.turn = 1;
            } else {
                ticTacToe.turn = 0;
            }
        }
    })



    socket.on('reset', function (data) {
        console.log(data)
        if (data === gameId) {
            getTicTacToe.forEach(element => {
                element.innerHTML = '';
            });
            ticTacToe.reset();
            console.log(ticTacToe)
        }
    });


    exitGame.onclick = () => {
        console.log('clicked')
        socket.emit('exit room', { gameId, playerId });
    }
}

reset.onclick = () => {
    socket.emit('reset', gId)
}

socket.on('room exited', game => {
    if (game.gameId === gId) {
        console.log(game);
        onlinePlayers.innerHTML = `Opononet left the game, online players: ${game.players.length}`;
        const gameEl = document.getElementById('game');
        rooms.style.display = 'block';
        gameEl.removeAttribute('class');
        gameEl.style.display = 'none';
        reset.click();
    }
    const item = document.getElementById(game.gameId);
    item.removeAttribute('disabled')
})

socket.on('disconnected socket', socketId => {
    console.log(socketId)
})